### PR TITLE
Add DTMEditor

### PR DESCRIPTION
**Pull request by Olly-**
Added DTM Editor. Like ACA it can be launched from a script:
```pascal
procedure DTMEditor(Title: String; out DTM: String);
```

img

Also:
- Disabled FormDesigner (currently only compatible with PS)
- Imported FPC version defines. Will update automatically and currently are:
  ```pascal
  {$IFDEF FPC_VERSION_3}  
  {$IFDEF FPC_RELEASE_0}
  {$IFDEF FPC_PATCH_4}
  ```

Now, a few minor things (getting SRL to compile etc) and we are ready for testing!

### CODE REVIEW

**Comment by KeepBotting** [comment]
We have a built-in DTM editor again! :sun_with_face:

**Comment by MerlijnWajer** [comment]
Are there plans to revive the formdesigner?

**Comment by Olly-** [comment]
@MerlijnWajer Yes but it's not just the syntax. It's quite unstable (lot's of crashes) so it's a bit more work, I think for now it's better to disable and get people testing a working Simba. 

As it's related I think a review on the whole LCL imports in Simba would be nice. It's quite bulky already and doesn't  work the best with lape's syntax. We could create our own components (think [imgGUI](https://github.com/ocornut/imgui) style) for a much easier to use system?

**Comment by Olly-** [comment]
@MerlijnWajer you got me, and multiple hours later...

Patched up the whole form designer

- outputs the correct code (and much nicer)
- moved into tools menu with the others
- re-sizeable
- added hints component buttons
- fixed font size not being assigned
- fixed scrollbox panel not being aligned properly therefor default form appearing offscreen.
- form designer supported radiobuttons but lape lacked the export, exported now.
- cleaned up component naming to follow lazarus style (TRadioButton0 > RadioButton1)

img

**Comment by MerlijnWajer** [comment]
♥

**Pull request merged**
