### PR TITLE
Add ACA

### PR DESCRIPTION
**Pull request by Olly-**
Added ACA (Auto Color Aid) as a tool for Simba.

Accessible from a script too with:
```pascal
// Run ACA GUI
procedure ACA(out CTS, Color, Tolerance: Int32; out Hue, Sat: Extended); 
// gui-less best color calculation.
procedure ACA(Colors: TIntegerArray; CTS: Int32; out Color, Tolerance: Int32; out Hue, Sat: Extended);
```
Requires #411 to be merged

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
@NielsAD - what do you think?

**Comment by MerlijnWajer** [comment]
BTW, I would not have an overloaded function that depending on how it's called (overloaded args) presents a UI or not. That's just odd. :)

**Comment by slackydev** [comment]
This is quite useful for a handful of scripts
1. Can spawn the GUI from a script, and have the user select colors for setup, and get a good color for the execution. Eg, for RS combat scripts, but also A LOT else..
2. Can get fancy and dynamically update colors on the go by using the latter GUI-less method which takes several colors to output a single good color.
These are just two obvious things we gain, I am sure some people could get creative with it.

Further more, I agree with the idea that Olly has about adding DTM editor, as well as ACA to Simba's core, as these two features are basically essential for Simba. 

You don't create a DTM manually, that's madness, hence Simba should at it's core have a DTM editor. The same goes for ACA in how it completes the CTS2. Modifiers requires it.


@MerlijnWajer I agree with you on the overloads. Perhpas teh GUI method could be named the more obvious: `ACAGUI` or similar.

**Comment by MerlijnWajer** [comment]
Мерси

**Pull request merged**
