### PR TITLE
The native XML support and a script code commenter

### PR DESCRIPTION
**Pull request by CynicRus**
Inbuilt class for the xml working from a Simba script. Test script
included. Also improvement for the IDE. Feature for the script comment by hotkey ctrl + /, uncomment also supported.

### CODE REVIEW

**Comment by ollydev** [comment]
Cool! You left in rs232test.simba though!

Whoever accepts this make sure you merge the commits (dropdown on the green accept button).

**Comment by JohnPeel** [comment]
Can you separate the two features into their own pull requests?

**Comment by CynicRus** [comment]
Its maybe hard:) But I do that if that necessary.

**Comment by JohnPeel** [comment]
> Its maybe hard:) But I do that if that necessary.

Not totally necessary, but would be preferred.

Usually when you send in code to be merged you separate things to different pull requests.

**Comment by ollydev** [comment]
Your code commenter was added in #480 (thanks to daileyj93). XML support would still be nice in a new PR.

**Pull request closed without merging**
