### PR TITLE
Update simbaunit.pas

### PR DESCRIPTION
**Pull request by riwu**
Copy color picker coordinate to clipboard for convenience

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
Genious!

**Comment by nielsAD** [comment]
This sounds like something that would benefit from having a setting to let the user opt-out.

**Comment by WarPie** [comment]
I agree with what niels said, it would be inconvenient to lose whatever already exist in the clipboard.

**Comment by MerlijnWajer** [comment]
(See Pull request #360)

**Pull request merged**
