### PR TITLE
Functionlist improvements + additions.

### PR DESCRIPTION
**Pull request by Olly-**
Added Compiler and Classes section to the function list: http://i.imgur.com/ScMD4mb.png

Added some neat features to our parser:
* Tell if a procedure is a overload
* Tell if a procedure is a override
* Get the type name of a type method.

Also added a small parser test to tests/

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
It looks OK I think. :) @JohnPeel what do you think?

**Comment by JohnPeel** [comment]
It looks fine, we can exclude " Projects/Simba/framefunctionlist.lfm " when merging it's just from him moving the form in Lazarus.

I'd also like to know why these are strings? (https://github.com/MerlijnWajer/Simba/pull/331/files#diff-85dbe1604661b843d48b4bab90839ee1R963)

**Comment by Olly-** [comment]
@JohnPeel I could add a SearchedOverload, SearchedOverride boolean then I could store them as booleans. But do booleans *always* default as false in fpc?

**Comment by JohnPeel** [comment]
@Olly- "Boolean"s do, but you should still initialize anything, I don't mind how it is now, though I think Lape's TInitBool idea is great.

**Comment by MerlijnWajer** [comment]
Thanks, be sure to get people to test this. :)

**Pull request merged**
