### PR TITLE
update FilterPointsPie

### PR DESCRIPTION
**Pull request by SRLSolaire**
fixed compilation error:
- parenthesis in if statement,
- max, min(startD, endD) changed to maxE, minE(startD, endD) to match types

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
Hi! It seems you're using the libmml branch, which is outdated. Can you check if this issue is present in the master branch?

**Comment by WarPie** [comment]
Not sure what's up here, but everything works as it should on Master. I even tested the function. The changed logic doesn't make any sense either.

**Comment by SRLSolaire** [comment]
Oh, my bad then. Is it possible that the update in master didn't get pushed to simba? Everything I have is up to date and the function doesn't work like the one in master.

**Comment by WarPie** [comment]
Try the latest release candidate: https://villavu.com/forum/showthread.php?t=116407

**Comment by SRLSolaire** [comment]
This only occurs when crossing the angle of 0 degrees. Trying to filter points from 270 to 20 should yield only the points inside the green arc. 
fpp sc

**Comment by JohnPeel** [comment]
This commit doesn't change anything on the current master (simba-1.2).

**Pull request closed without merging**
