### PR TITLE
getFiles on unicode file name

### PR DESCRIPTION
**Pull request by riwu**
Fix Issue #182 
Didn't change it for GetDirectories() since it strangely works on unicode char with just FindFirst()

Also added some misc settings

Btw, https://github.com/MerlijnWajer/Simba/blob/master/Projects/Simba/newsimbasettings.pas#L837
this already gives the obj a default value, why do we still need https://github.com/MerlijnWajer/Simba/blob/master/Projects/Simba/newsimbasettings.pas#L555
Isn't it redundant to have both?

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
Changes seem fine. With regards to your question, I'd have to dig into a bit more to be sure, but I don't think they are redunant. One of them is just defining what the default value should be, no? The other one just returns a default value if it exists.

**Comment by MerlijnWajer** [comment]
(Thanks, btw)

**Comment by riwu** [comment]
Whenever u add a new setting, you would add a corresponding procedure that gives it a default value.
Hence there will always be a default value (FValueSet is always true), hence we can just use GetValue() instead of GetDefValue(val: Boolean) (the argument will never be used in practice)

**Comment by MerlijnWajer** [comment]
Can you file an issue for this? Then we can discuss it at that issue.

**Pull request merged**
