### PR TITLE
Fix TMufasaBitmap.SaveToFile memory leak

### PR DESCRIPTION
**Pull request by riwu**
https://github.com/MerlijnWajer/Simba/issues/303#issuecomment-57053656
That only fixed half of the leak as there's another leak here (doesn't get freed if SaveToFile fails)

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
You can use try ... except ... finally here, right? So then you can always free the bitmap even if the saving fails? :)

**Comment by nielsAD** [comment]
I also think LoadFromRawImage should be moved inside the try block. Nice catch, though; this was very ugly code. :grin:

**Comment by riwu** [comment]
@MerlijnWajer wouldn't statements after the try block still be executed, unless u exit/encountered another error in except/finally block? So the behaviour in this case will be the same without the finally?

@nielsAD added ur suggestions. yeah code is ugly, another way is to have a single try statement but we would have to check the filename again to free the correct variable...

**Comment by MerlijnWajer** [comment]
@riwu: You are right, either way works.

**Comment by MerlijnWajer** [comment]
Thanks! :)

**Pull request merged**
