### PR TITLE
Added resizable support to EIOS.

### PR DESCRIPTION
**Pull request by patriq**
### Motivation

The current EIOS implementation lacks 2 things:

1. Only sets its dimensions when creating the target, which leads to pixel data not being read properly if the dimensions of the target are to ever change over time. An example of this behavior can be seen here in these two images:
   Screenshot before rezising 
   Screenshot after rezising

2. A way to change the address of the original pixel buffer provided in `GetImageBuffer`. Not being able to do this, forces the developer to pre-allocate a big enough buffer to account for possible resizes that might happen over time. Doing so is not efficient given resizes might not be frequent and given the different amount of screen dimensions that are on the market these days.

So I addressed these two issues in the following manner:
1. The first one was fixed by asking the target for its dimensions when the buffer is updated. 

2. The second one was fixed by adding a new function to the EIOS specification, called `UpdateImageBufferEx`, that allows the developer to change the pixel buffer if he so desires to account for possible memory re-allocations.

### Changes

So after merging this PR, the following will be consulted when an image buffer of an EIOS target needs to be updated:
- `UpdateImageBuffer: procedure(target: pointer)`: This is a procedure that receives the image buffer pointer and hopefully updates the contents of such pointer.
- `UpdateImageBufferEx: function(target: pointer): prgb32`: Works similar to the `UpdateImageBuffer` procedure, but it is a function instead and uses the result as the new image buffer pointer of the target.
- `UpdateImageBufferBounds: procedure(target: pointer; sx,sy,ex,ey: integer)`:  Does the same as `UpdateImageBuffer` but it specifies which region of the image buffer requires to be updated.

Because they all have the same "responsibility", of keeping the image buffer updated, they are consulted exclusively and have the following priority (from highest to lowest): 
1. `UpdateImageBufferBounds` is checked first
2. `UpdateImageBufferEx` is checked second
3. `UpdateImageBuffer` is checked last

Note that these changes ensure backwards compatibility since both `UpdateImageBuffer` and `UpdateImageBufferBounds` still exist!

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
This looks good to me. @BenLand100 ?

**Comment by MerlijnWajer** [comment]
I feel like it would make sense to also update the documentation, btw.

**Comment by BenLand100** [comment]
The only issue I see with this is there are now three methods for requesting buffer updates: EIOS_UpdateImageBuffer EIOS_UpdateImageBufferEx and EIOS_UpdateImageBufferBounds, while only one of them should/will be used.

Ex provides the ability to change the buffer address, and Bounds provides hints about which region needs updating. I'm not entirely sure why the latter was added, but as it stands there's no way to do both. 

That being said, it's probably fine. If combined functionality is needed, it can be added later.

**Comment by patriq** [comment]
@MerlijnWajer Will update the documentation as well :+1:

**Comment by MerlijnWajer** [comment]
Let me know when you update the documentation.

**Comment by ollydev** [comment]
No documentation currently exists for EIOS but @Patriq has updated the PR with documentation about the UpdateImageBuffer methods.

**Pull request merged**
