### PR TITLE
[WIP] Neural network classifier

### PR DESCRIPTION
**Pull request by DrDub**
This PR seeks to integrates the excellent [Neural-API](https://github.com/joaopauloschuler/neural-api) by Joao Paulo Schwarz Schuler as a TMusafaBitmap's `ClassifyBitmap` new method.
    
It includes a model trained on 60,000 images over 100 different classes (CIFAR-100) but other models can be trained using Neural-API.

Rather than a finished integration, this PR is a question: is this something you would be interested in adding into Simba? (I love the idea of a multiplatform desktop scripting environment and it might be possible to extended into a full RPA open source solution.)

If this goes in line with the direction of the project, then there is the question of whether to integrate this into Simba or package it as an extension. (Integrating the CIFAR classifier adds extra 3.2Mb to Simba.)

If we want to integrate this into Simba proper, the current code has a number of issues I'd need your help and guidance:

* The neural network model is kept in disk. It would be nice to compile it as a resource and load it directly from the executable.
* The neural network model is loaded every time the method is called. I tried setting it up as  a global variable but that did not work (most probably because each script executes in a separate environment).
* `TMusafaBitmap.ResizeBilinear` produces inferior results to `TBitmap.StretchDraw` and that impacts the predictions significantly (the classifier works on 32x32 images).
* The result of the model are not stable (I don't know whether that's a problem in neural-api or an incompatibility with the execution environments, it'll take a deeper debugging to find out).

Here is a little Simba script showcasing the behaviour of the new method:

```pascal
program classifyexample;
var
  m: TMufasaBitmap;
  labels: TStringArray;
  scores: TSingleArray;
  bestMatch: String;
  i: Integer;
begin
  for i := 1 to 10 do
  begin
    m := TMufasaBitmap.CreateFromFile('/path/to/some/image/with/a/pear');
    m.ClassifyBitmap(labels,scores,bestMatch);
    WriteLn(bestMatch);
    m.Free;
end;
end.
```

To see all the scores:

```pascal
program classifyexample;
var
  m: TMufasaBitmap;
  labels: TStringArray;
  scores: TSingleArray;
  bestMatch: String;
  i: Integer;
begin
  m := TMufasaBitmap.CreateFromFile('/path/to/some/image');
  m.ClassifyBitmap(labels,scores,bestMatch);
  for i := Low(scores) to High(scores) do
     WriteLn(i, ' ', labels[i], ': ', scores[i]);
  WriteLn(bestMatch);
  m.Free;
end.
```

### CODE REVIEW

**Comment by BenLand100** [comment]
My $0.02, something like this is too heavy to be included in the core program, and would be a maintenance nightmare. Creating an extension/plugin would be better. 

You should also define a context (record with state variables) for this framework, and have methods to create/destroy/attach to a context, if you want persistence across scripts.

**Comment by ollydev** [comment]
This definitely belongs in a plugin. I agree with Ben that all of this just for image classifier is a bit of a nightmare.
It is possible that as neural-api grows and can perform tasks like realtime object detection, the whole API can be imported into scripts.

In it's current state a plugin would be ideal for this, and could be quite a neat "drop in" feature.

----

If not aware you can extend TMufasaBitmap from a plugin with something like this:

```pascal
addGlobalFunc('function _ClassifyBitmap(bitmapData: PRGB32; bitmapWidth, BitmapHeight: Integer; out labels: TStringArray; out scores: TSingleArray; out Best: String): Boolean); native;', @_ClassifyBitmap);

addCode(
  'function TMufasaBitmap.ClassifyBitmap(out labels: TStringArray; out scores: TSingleArray; out Best: String): Boolean;' + LineEnding +
  'begin' + LineEnding +
  '  Result := _ClassifyBitmap(Self.GetData(), Self.GetWidth(), Self.GetHeight(), Labels, Scores, Best);' + LineEnding +
  'end;'
)
```

See this plugin for more infomation: https://github.com/ollydev/SimpleOCR/blob/master/simbaplugin.inc

---

Other things:

1) You noted `TMufasaBitmap.ResizeBilinear` but `TMufasaBitmap.Resize` _should_ give the same result as LCL's `StretchDraw` (nearest neighbor). 
2) Scripts are indeed executed in a new process each time. Using a global variable will mean you don't have to load the network every time the method is executed, only once per script run.
3) Simba uses fpcres to bundle data (like openssl binaries) into the executable, this should be possible in a plugin too:
 - Generating the resource file(s): https://github.com/Villavu/Simba/blob/simba1500/Third-Party/openssl/INFO
 - Loading using `TResourceStream` https://github.com/Villavu/Simba/blob/simba1500/Source/simba.openssl.pas#L65 (Simba is compressing the resource files, and is obviously not needed)

**Comment by slackydev** [comment]
I believe this goes in line with what Simba aims to achieve, it takes it's capabilities when it comes to automation up a notch.

I am unsure how much of a maintenance nightmare it would be, it's indeed a big library, and should it's maintenance halt, given that there's a single contributor to it, then we could eventually see problems after breaking Lazarus changes.

That aside, I do think there needs to be more, notably more, for it to valuable in Simba. Would also prefer a solution that allows users to train a network as well, without having to use FPC/Lazarus. As for exporting the whole API which @ollydev mentioned, I'd prefer to see a simplified/minimalized API as well, wherever possible. What I think would be most valuable from the developer/scripters perspective is classification, and localization of objects in images though.

Maybe it belongs in a plugin, maybe it doesn't. The only reason plugin is mentioned is because it can potentially lead to much work maintaining, some time in the future. Then it has to bring a lot of value.

**Comment by DrDub** [comment]
Thanks for taking the time to reply.

On the good news front, with @ollydev's comment that  `TMufasaBitmap.Resize` was equivalent to `TBitmap.StretchDraw` I managed to streamline the code and with some feedback from Neural API creator managed to fix the instability.

So to have this in Simba core I can summarize it'll need to:
1. Be a library with a larger dev base.
2. Have an object detector not only a classifier.
3. Be able to be fine-tuned ("transfer learned") within Simba proper using examples gathered by the users.

The first one is a little bit of a chicken-and-egg issue and won't be solved any time soon.

The second one, Neural API does not ship an example object extractor but there are many proposed in the literature. I'll talk with the author of Neural API to see if something like a YOLOv2 might be feasible to implement on it.

The last one, I can help. I only included the Neural API files to execute models, but the ones for training are a few more libraries. The model in the PR took about 10 hours to train on CPU. Fine tuning models is much faster (the training process starts from the already trained model available to the users). And the UI bits should be straightforward (given Simba is written in Lazarus).

Feel free to close this PR if you think the plugin decision is clear.

**Comment by BenLand100** [comment]
It's not so much the size of the dev base for the library as it is whether the folks maintaining Simba have the time/will/skill to keep this up to date and whether Simba has a release cycle amenable to such development. The latter is maybe the most important: if this API needs changes, it's a lot easier to have end users update a plugin that you have control over than to get Simba dev team to release a new software version. You'll find no significant limitations to packaging within a plugin vs in core, only benefits (imo).

**Comment by joaopauloschuler** [comment]
> The model in the PR took about 10 hours to train on CPU.

@DrDub, just out of curiosity, did you run with AVX, AVX2 or AVX512 defines in release mode? How many CPU cores did you run with? How many epochs?

**Comment by DrDub** [comment]
> It's not so much the size of the dev base for the library as it is whether the folks maintaining Simba have the time/will/skill to keep this up to date and whether Simba has a release cycle amenable to such development. The latter is maybe the most important: if this API needs changes, it's a lot easier to have end users update a plugin that you have control over than to get Simba dev team to release a new software version. You'll find no significant limitations to packaging within a plugin vs in core, only benefits (imo).

I think this point is key. Before I was concerned about building on multiple architectures as I saw the GitHub actions Simba uses from MacOS includes a binary signing secret I'm not familiar with MacOS toolchain to obtain. But looking at the Tesseract plugin, for dynamic libraries is not needed.

I'll try to put this together as a plugin. Thanks for your help.

**Comment by DrDub** [comment]
> > The model in the PR took about 10 hours to train on CPU.
> 
> @DrDub, just out of curiosity, did you run with AVX, AVX2 or AVX512 defines in release mode? How many CPU cores did you run with? How many epochs?

I did not modify the include files in your repository (and I'm looking at the files and I think I was running a debug build) nor the number of epochs (it ran for 300 epochs). The final test line was:

```
FINAL TEST,,,,,,,,41653,0.6592,1.2365,0.9067
```

That was run on an i9 with 20 cores. I'll open an issue in your project to discuss about object recognition :grin:

**Comment by ollydev** [comment]
Pretty much everything in Simba that isn't standard FPC/Lazarus started off as a plugin, once it's well developed and useful (bit more than image classification!) it's normally added.
Also I have no problem merging anything this library eventually, it's fully written in FPC and can even be defined in/out and have two Simba binaries if needed.

Just to note macOS signing is not absolutely needed, I was trying to get rid of apple and constant dumb warnings. Signing currently makes no difference.

**Comment by slackydev** [comment]
I am still interested in this project, not sure if a plugin was ever attempted, or further work was done in regards to YOLO implementation using Neural-API. 


Also I'd like to point out something regarding:
> *TMusafaBitmap.ResizeBilinear produces inferior results to TBitmap.StretchDraw and that impacts the predictions significantly (the classifier works on 32x32 images).*

One can change the way it's attacked by first downsampling which however with the current implementation always keeps aspect ratio, so single input for scale.

Now we can first downsample to a value just above our desired size:
`a := img.Downsample(Min(Ceil(img.Height / 128), Ceil(img.Width / 128)));`
Followed by a resize using bilinear to get the exact fit:
`b := a.Resize(EImageResizeAlgo.BILINEAR, 128,128);`

Bilinear resize down to 128x128 from 5760x3840
image

Downsample -> Bilinear
image

It will lose some sharpness, but way less noisy, and therefor better suited, hopefully this is comparable to StretchDraw

**Edit:** We can maintain more sharpness if we dont downsample all the way, but instead only halfway, and let the bilinear interpolation do it's thing on the now somewhat overly smooth image:

`a := img.Downsample(Min(Ceil(img.Height / 256), Ceil(img.Width / 256)));`
Followed by a resize using bilinear to get the exact fit:
`b := a.Resize(EImageResizeAlgo.BILINEAR, 128,128);`
image

Final of a dog (originally 600x600) when using this process 
image

**Pull request closed without merging**
