### PR TITLE
Add github package system

### PR DESCRIPTION
**Pull request by ollydev**
**NOTE: PR is big because I need to use the FPC 3.0 HTTP client. Once Simba has moved to FPC 3.0 the ```package_internets/``` directory can be deleted and everything should compile without issues.** 

First of all OpenSSL has [changed licenses](https://www.openssl.org/blog/blog/2017/03/22/license/) which makes this all possible, For windows I ship the binary's packed in Simba and extract them on startup, on linux `apt-get install openssl-dev` will do the job.

The package system uses github releases to easily manage, install and update anything. This can eventually replace the current updater system we use in extensions. 

A optional basic installation mode is enabled when a [.simbapackage](https://github.com/SRL/SRL/blob/master/.simbapackage) file is added to the repository, else a custom installation is available for any github release.

Packages do not auto update, there is too many issues when files (mainly plugins) are already in use and cannot be moved or deleted to work well. But it will automatically check for updates and update the button accordingly 

Finally, the changes that aren't just copying FPC 3.0 files are adding `package.pas`, adding openssl.dll resources files and modifying `simbaunit.pas` slightly.

(Will fix linux support ASAP)

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
This looks great. How should we move forward to switch to FPC 3.0? Would prefer that be a separate PR.

**Comment by Olly-** [comment]
The switch to FPC 3.0 is a big one, FPC changed how strings & arrays were handled so all FPC plugins will have to re-built to work. If we do this I suggest it would be under a pretty major update - where everything is neutralised in a big update I would suggest:

- Packages (this), with updating all current updaters to utilise it (Font, Plugins, Includes).
- Finally ditch PS.  
- With removing PS comes the issue of extensions, lape extensions don't play as nice as PS and with packages added the major of use of extensions (updaters) aren't needed. The other main use is DTM editor, which I have [recreated](https://github.com/Olly-/Simba/tree/1.3/Projects/DTMEditor) in FPC and is a simple merge. Extensions could be removed.
- Finally a repository cleanup, it's got quite messy over the years. :D

**Comment by slackydev** [comment]
I hope there isn't any problems with this getting into Simba seeing as how it's not merged yet, it's a very useful tool that simplifies a lot for us Simba users.

**Comment by MerlijnWajer** [comment]
How do I re-trigger travis to run?

**Comment by MerlijnWajer** [comment]
And yes, please update it to fpc 3.0.

**Pull request closed without merging**
