### PR TITLE
Added GetProcessMem

### PR DESCRIPTION
**Pull request by riwu**
Get the working set size of a process given its PID.

Please check if i did anything redundant/missed out anything.
Need to GetMem then free ppsmemCounters?

EDIT: added check for OpenProcess (thanks slacky!). Since GetProcessMemoryInfo() should succeed if OpenProcess succeeded, checking that is omitted.

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
There a few things I want to check:
1) Should this be in the IOManager (I see GetProcesses is there, may be a mistake)
2) Does this work on Linux
3) Your questions

I'll try to give feedback ASAP

**Comment by JohnPeel** [comment]
Prob should not be on IOManager, that was my mistake, I put GetProcesses there as it's where all the other os specific crap was.

Maybe we should move these to MMLAddon, or possibly to a Misc unit with a method for adding to Lape?

**Comment by WarPie** [comment]
I think something like: `MMLAddon/OS.pas` which uses `MMLAddon/OS/windows.inc` & `MMLAddon/OS/xlib.inc` depending on OS would be nice, funcinallity and such would be mainly added to the "inc"-files.
That way we get some nice structure that would promote adding new OS-related functions.

**Comment by MerlijnWajer** [comment]
@WarPie: Sound sensible

**Comment by nielsAD** [comment]
@CynicRus Also exposed a similar API with `TMemoryWorker` in #372. Not sure if we need both.

**Comment by ollydev** [comment]
2361 days later. It is implemented! 🤣 
51e5c0311aeffe5088b6167337d11ea01ce98821

**Pull request closed without merging**
