### PR TITLE
Fixed out of bounds errors in FindColors*

### LINKED ISSUE #402: [Linux] FindColors, FindColorsTolerance, FindColorsSpiralTolerance broken
If you try to use any FindColors* (And most likely any finding func which returns a TPA) it'll crash the script returning "Error: Exception in safecall method at line 5" most likely crashing Simba as well. 
This happens to a 64/32bit with fpc 2.64 and 64/32bit with fpc 3.0 but doesn't seem to apply to Windows.

### PR DESCRIPTION
**Pull request by Harrierr**
Fixes #402

### CODE REVIEW

**Comment by JohnPeel** [comment]
`Result := C > 0;
SetLength(Points, C);
if Result then
  Move(ClientTPA[0], Points[0], C * SizeOf(TPoint));`

**Comment by MerlijnWajer** [comment]
I think @JohnPeel's suggestion is probably better.

**Comment by MerlijnWajer** [comment]
Can you change the code to incorporate his suggestion?

**Comment by nielsAD** [comment]
Thanks!

**Pull request merged**
