### PR TITLE
Function List & File Browser

### PR DESCRIPTION
**Pull request by Olly-**
The old function list had a couple of issues:
- Was constantly running, even with no script changes.
- The includes node wouldn't always update when it was suppose to.
- Source was separated in two different files randomly
- It wouldn't give you a true overview of the file (would move methods under the type node etc) which is not expected.

I fixed all of this and added header hint on mouse over.

IMG

***

Integrated a file browser with where notes are, you can toggle the visibility of either (or both) in the view menu. It also allows you to open a file in Simba or externally (with whatever  program your OS decides).

IMG 

***

All this required a lot of changes in `simbaunit.pas` so I was cleaning up that file a lot while developing. did some local testing & scripting to some of the major bugs - only found one!

:)

### CODE REVIEW

**Comment by Olly-** [comment]
@nielsAD The test failed because the docs broke. Can we remove whatever is causing the issue?

At a later date we can look into doing documentation properly with Travis & releases (like I suggested for SRL).

(for anyone else this is what i'm talking about doing with SRL)
https://github.com/Olly-/ItemFinder/blob/master/.travis.yml deploys to 
https://github.com/Olly-/ItemFinder/tree/gh-pages on release, which is hosted at http://olly-.github.io/ItemFinder/

**Comment by nielsAD** [comment]
It's failing because of

```
(line   30) broken    https://villavu.com/ - <urlopen error timed out>
```

**Comment by MerlijnWajer** [comment]
OVH seems to have some network issues. Or the machine. Working on it, but no ETA for fixing it. It just works "sometimes".

**Comment by MerlijnWajer** [comment]
Cool!

**Pull request merged**
